### ISSUE TITLE
When saving call flow name contains a "/", script errors

### ISSUE THREAD

**Issue by daviddewell1973** [aws-samples/amazon-connect-copy#1]
When saving call flows or queues (I would imagine all names) contains a "/", the script errors when writing the file.

**Comment by kjacky** [comment]
Thank you David for your report. I have encoded "/" as "%2F" to avoid it being mistakened as a path character. This change allows slashes in flow names and module names. Committed in 2f793c7.

**Comment by kjacky** [comment]
Issue resolved for all special characters in all component names.
