### ISSUE TITLE
Trouble with Creating new Routing Profiles

### ISSUE THREAD

**Issue by PercDev23** [aws-samples/amazon-connect-copy#14]
Hello. This looks very useful! Thanks for the effort. I tried this tonight but it failed at line 603 of the copy command. Let me know if you have any suggestions or ideas. Thank you again for your efforts.

Parameter validation failed:
Unknown parameter in input: "NumberOfAssociatedQueues", must be one of: InstanceId, Name, Description, DefaultOutboundQueueId, QueueConfigs, MediaConcurrencies, Tags
Unknown parameter in input: "NumberOfAssociatedUsers", must be one of: InstanceId, Name, Description, DefaultOutboundQueueId, QueueConfigs, MediaConcurrencies, Tags

**Comment by timothygabriel** [comment]
Also ran into this.  It looks like in AWSCLI version 2.7.30, the describe-routing-profiles was updated to include additional fields from the api in the output JSON.  However, the create-routing-profile command does not accept these fields, and so it errors out on the creation.

As a temporary measure, I ran the scripts with version 2.7.29.  The prior version installs are here: https://docs.aws.amazon.com/cli/latest/userguide/getting-started-version.html.  You will likely want to update the CLI afterwards if you need the features added by the updated CLI.

**Comment by NehaRana03** [comment]
> Also ran into this. It looks like in AWSCLI version 2.7.30, the describe-routing-profiles was updated to include additional fields from the api in the output JSON. However, the create-routing-profile command does not accept these fields, and so it errors out on the creation.
> 
> As a temporary measure, I ran the scripts with version 2.7.29. The prior version installs are here: https://docs.aws.amazon.com/cli/latest/userguide/getting-started-version.html. You will likely want to update the CLI afterwards if you need the features added by the updated CLI.

Thank you Tim for posting this solution:-) It is going to help me for sure! But I have one concern as I hope that having too many installations of aws-cli on my machine is not going create a ".dll hell" kind of problem. Just concerned before installing version 2.7.29 over my current version viz. 2.8.8. Your quick response is appreciated.

**Comment by kjacky** [comment]
Thank you all for your report. I have fixed the issue in version 1.3 and tested successfully on AWS CLI 2.8.6. Please download the new script and try again.
