### ISSUE TITLE
I am also getting same error while creating routing profiles

### ISSUE THREAD

**Issue by NehaRana03** [aws-samples/amazon-connect-copy#15]
Parameter validation failed:
Unknown parameter in input: "NumberOfAssociatedQueues", must be one of: InstanceId, Name, Description, DefaultOutboundQueueId, QueueConfigs, MediaConcurrencies, Tags
Unknown parameter in input: "NumberOfAssociatedUsers", must be one of: InstanceId, Name, Description, DefaultOutboundQueueId, QueueConfigs, MediaConcurrencies, Tags

**Comment by kjacky** [comment]
Thank you @NehaRana03 for your report. I have fixed the issue in version 1.3 and tested successfully on AWS CLI 2.8.6. Please download the new script and try again.
