### ISSUE TITLE
Error Creating Routing Profiles

### ISSUE THREAD

**Issue by nihkilrendu** [aws-samples/amazon-connect-copy#16]
I am getting the below error
<html>
<body>

Routing Profiles
Creating 1 routing profiles
 1. routing_Booking_Default.json

 Parameter validation failed:
Unknown parameter in input: "NumberOfAssociatedQueues", must be one of: InstanceId, Name, Description, DefaultOutboundQueueId, QueueConfigs, MediaConcurrencies, Tags
Unknown parameter in input: "NumberOfAssociatedUsers", must be one of: InstanceId, Name, Description, DefaultOutboundQueueId, QueueConfigs, MediaConcurrencies, Tags

</body>
</html>

**Comment by kjacky** [comment]
Thank you @nihkilrendu for your report. I have fixed the issue in version 1.3 and tested successfully on AWS CLI 2.8.6. Please download the new script and try again.
