### ISSUE TITLE
Error with connect_copy command

### ISSUE THREAD

**Issue by beibeixhb** [aws-samples/amazon-connect-copy#2]
Hi,

I have completed the connect_save for both source and target instances, connect diff, and dry run, when I proceed with the actual connect_copy command, it completed HOOP creation, routing profile creation, and queues creation, when it came to contact flow, I got the following error and I attached the screenshot of the JSON files in target instance folder:

Creating 44 contact flows
1. flow_AniTokenTestContactFlow.json
2. flow_AzmanyTestContactFlow.json
3. flow_C2CIntegrationTest-Contact-Flow.json
4. flow_Caracara-Developer-Contact-Flow.json
5. flow_Caracara-QA-Contact-Flow.json
6. flow_ContactFlowTest.json
7. flow_DSARConnect.json
8. flow_Developer-Contact-Flow.json
9. flow_HarshithChatDisconnectFlow.json
10. flow_HarshithChatTest.json
11. flow_HonwanhContactFlow.json
12. flow_IBLISKAV%20-%20Test%20Allocation%20Routing.json
13. flow_JanumbChatTest.json
14. flow_LhsienChatTest.json
15. flow_LiveMediaStreaming.json
16. flow_Load_Test.json
17. flow_Load_Testing_Queue_Flow.json

Error parsing parameter '--content': Unable to load paramfile file://cs-connect-gamma-na-non-saml/flow_Default customer queue.json: [Errno 2] No such file or directory: 'cs-connect-gamma-na-non-saml/flow_Default customer queue.json'

Error at line 986. Recommended actions:
Make sure all required prompts exist in the target instance, and
Install the latest AWS CLI:[ https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html](https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html) .
Error:

![Screen Shot 2022-03-08 at 4 19 00 PM](https://user-images.githubusercontent.com/17655045/157348171-459cb40d-550b-4185-896d-0ec21c14db72.png)

**Comment by kjacky** [comment]
Thank you Haobo for your report. The file names have been encoded since the last version to handle special characters in component names. There was a bug in the default flow names which need to be encoded as well. This has been fixed in commit [e351234](https://github.com/aws-samples/amazon-connect-copy/commit/e35123463306ea92e1d19eb69beb5acc96b1ab81) .
