### ISSUE TITLE
Missing contact flow descriptions

### ISSUE THREAD

**Issue by themarkyates** [aws-samples/amazon-connect-copy#36]
I copied various flows from one instance to an other perfectly fine but I noticed descriptions were missing on the imported flows

**Comment by kjacky** [comment]
Thank you @themarkyates for your report. This issue will be addressed in the next release v1.3.4. Thank you for your patience.

**Comment by themarkyates** [comment]
Thanks

**Comment by kjacky** [comment]
Version 1.3.4 has been pushed to the `development` branch, and will be released to `main` after more testing. Feel free to try it out from the `development` branch @themarkyates .

**Comment by themarkyates** [comment]
@kjacky I have tested the new version of the scripts 1.3.4 and I don't seem to get the descriptions to copy across with the flows
